In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [5]:
b = a.T
print(b)

[1 2 3 4 5]


In [6]:
c = np.array([[1,2],[3,4]])
print(c)

[[1 2]
 [3 4]]


In [7]:
d = c.T
print(d)

[[1 3]
 [2 4]]


BROADCASTING

In [8]:
e = np.array([1,2,3])
print(e)
g = e+5
print(g)

[1 2 3]
[6 7 8]


In [9]:
h = np.array([1,2,3])
print(h)
i = h+[1]
print(i)

[1 2 3]
[2 3 4]


In [13]:
j = np.array([[1,2,3],[4,5,6]])
print(j)
z1 = np.array([100])
z2 = j+z1
z2

[[1 2 3]
 [4 5 6]]


array([[101, 102, 103],
       [104, 105, 106]])

In [14]:
j = np.array([[1,2,3],[4,5,6]])
print(j)
z1 = np.array([100,200])
z2 = j+z1
z2

[[1 2 3]
 [4 5 6]]


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [15]:
j = np.array([[1,2,3],[4,5,6]])
print(j)
z1 = np.array([100,200,300])
z2 = j+z1
z2

[[1 2 3]
 [4 5 6]]


array([[101, 202, 303],
       [104, 205, 306]])