In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [5]:
b = np.zeros([3,3])
print(b)
print(b.ndim)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2


In [6]:
c = np.ones([3,3])
print(c)
print(c.ndim)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
2


In [7]:
d = np.ones([3,3],dtype=int)
print(d)
print(d.ndim)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
2


3D -> [No. of Matrix, Rows, Columns]

In [13]:
e = np.ones([3,4,2],dtype=int)
print(e)
print(e.ndim)

[[[1 1]
  [1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]
  [1 1]]]
3


In [44]:
k = np.ones([3,2,2,2,3],dtype=int)
print(k)
print(k.ndim)

[[[[[1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]]]


  [[[1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]]]]



 [[[[1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]]]


  [[[1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]]]]



 [[[[1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]]]


  [[[1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]]]]]
5


In [47]:
l = np.ones([1,2,3,4,5],dtype=int)
print(l)
print(l.ndim)

[[[[[1 1 1 1 1]
    [1 1 1 1 1]
    [1 1 1 1 1]
    [1 1 1 1 1]]

   [[1 1 1 1 1]
    [1 1 1 1 1]
    [1 1 1 1 1]
    [1 1 1 1 1]]

   [[1 1 1 1 1]
    [1 1 1 1 1]
    [1 1 1 1 1]
    [1 1 1 1 1]]]


  [[[1 1 1 1 1]
    [1 1 1 1 1]
    [1 1 1 1 1]
    [1 1 1 1 1]]

   [[1 1 1 1 1]
    [1 1 1 1 1]
    [1 1 1 1 1]
    [1 1 1 1 1]]

   [[1 1 1 1 1]
    [1 1 1 1 1]
    [1 1 1 1 1]
    [1 1 1 1 1]]]]]
5


In [14]:
f = np.ones([4,3,5],dtype=int)
print(f)
print(f.ndim)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
3


In [24]:
g = np.array([1,2,3,4,5,6,7,8,9])
print(g)

[1 2 3 4 5 6 7 8 9]


In [25]:
h = g.reshape(3,3)
print(h)
print(h.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [27]:
i = h.flatten()
print(i)
print(i.ndim)

[1 2 3 4 5 6 7 8 9]
1


Arrange -> np.arrange(n,m,x) [n,m) Includes n but doesn't include m and with equal x spacing by 3rd Argument

In [29]:
j = np.arange(0,20,3)
print(j)

[ 0  3  6  9 12 15 18]


Linspace -> np.linspace(n,m,x) Includes both n and m and divides the range evenly provided by the 3rd Argument x

In [48]:
m = np.linspace(0,20,3)
print(m)

[ 0. 10. 20.]


In [49]:
n = np.linspace(0,20,6)
print(n)

[ 0.  4.  8. 12. 16. 20.]


random.rand -> gives random value till 1 for the given MxN matrix

In [54]:
o = np.random.rand(3,2)
print(o)
print(o.ndim)

[[0.67141776 0.46421813]
 [0.80326067 0.78056159]
 [0.88932434 0.07202566]]
2


In [55]:
p = np.random.rand(5)
print(p)
print(p.ndim)

[0.7439864  0.76277803 0.99649605 0.72494721 0.46238119]
1


random.ranf -> same like random.rand but doesn't give the value 1

In [57]:
q = np.random.ranf(6)
print(q)
print(q.ndim)

[0.03281165 0.36094898 0.60049993 0.15575076 0.26893133 0.44454041]
1


np.eye(m,n) -> gives the diagonal value as 1 and others as 0
numpy.eye(N, M=None, k=0, dtype=<class ‘float’>, order=’C’)

Parameters : 

R : Number of rows

C : [optional] Number of columns; By default M = N\

k : [int, optional, 0 by default]
Diagonal we require; k>0 means diagonal above main diagonal or vice versa.

dtype : [optional, float(by Default)] Data type of returned array.

In [62]:
r = np.eye(3,5)
print(r)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [63]:
r = np.eye(3,5,1)
print(r)

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [60]:
s = np.eye(3,3)
print(s)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [68]:
t = np.array([1,2])
print(t)
u = np.array([3,4])
print(u)
con = np.concatenate((t,u),axis=0)
print(con)

[1 2]
[3 4]
[1 2 3 4]


In [71]:
v = np.array([[1,2],[3,4]])
print(v)
w = np.array([[5,6],[7,8]])
print(w)
con = np.concatenate((v,w),axis=0)
print(con)
print("-------------")
con = np.concatenate((v,w),axis=1)
print(con)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
-------------
[[1 2 5 6]
 [3 4 7 8]]


In [72]:
x = np.array([1,2])
y = np.array([3,4])
z = np.add(x,y)
print(z)

[4 6]
