In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [5]:
b = np.zeros([3,3])
print(b)
print(b.ndim)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2


In [6]:
c = np.ones([3,3])
print(c)
print(c.ndim)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
2


In [7]:
d = np.ones([3,3],dtype=int)
print(d)
print(d.ndim)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
2


3D -> [No. of Matrix, Rows, Columns]

In [13]:
e = np.ones([3,4,2],dtype=int)
print(e)
print(e.ndim)

[[[1 1]
  [1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]
  [1 1]]]
3


In [44]:
k = np.ones([3,2,2,2,3],dtype=int)
print(k)
print(k.ndim)

[[[[[1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]]]


  [[[1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]]]]



 [[[[1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]]]


  [[[1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]]]]



 [[[[1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]]]


  [[[1 1 1]
    [1 1 1]]

   [[1 1 1]
    [1 1 1]]]]]
5


In [47]:
l = np.ones([1,2,3,4,5],dtype=int)
print(l)
print(l.ndim)

[[[[[1 1 1 1 1]
    [1 1 1 1 1]
    [1 1 1 1 1]
    [1 1 1 1 1]]

   [[1 1 1 1 1]
    [1 1 1 1 1]
    [1 1 1 1 1]
    [1 1 1 1 1]]

   [[1 1 1 1 1]
    [1 1 1 1 1]
    [1 1 1 1 1]
    [1 1 1 1 1]]]


  [[[1 1 1 1 1]
    [1 1 1 1 1]
    [1 1 1 1 1]
    [1 1 1 1 1]]

   [[1 1 1 1 1]
    [1 1 1 1 1]
    [1 1 1 1 1]
    [1 1 1 1 1]]

   [[1 1 1 1 1]
    [1 1 1 1 1]
    [1 1 1 1 1]
    [1 1 1 1 1]]]]]
5


In [14]:
f = np.ones([4,3,5],dtype=int)
print(f)
print(f.ndim)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
3


In [24]:
g = np.array([1,2,3,4,5,6,7,8,9])
print(g)

[1 2 3 4 5 6 7 8 9]


In [25]:
h = g.reshape(3,3)
print(h)
print(h.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [27]:
i = h.flatten()
print(i)
print(i.ndim)

[1 2 3 4 5 6 7 8 9]
1


In [29]:
j = np.arange(0,20,3)
print(j)

[ 0  3  6  9 12 15 18]
