In [3]:
print("Hello")

Hello


In [6]:
import numpy as np
a = np.array([1,2,3,4,5,6])
print(a)
print(a.ndim)

[1 2 3 4 5 6]
1


In [7]:
b = np.array([[1,2,3,4,5,6]])
print(b)
print(b.ndim)

[[1 2 3 4 5 6]]
2


In [10]:
c = np.array([[[1,2,3,4,5,6]]])
print(c)
print(c.ndim)

[[[1 2 3 4 5 6]]]
3


NDMIN is used to specify the Dimension of a given array

In [13]:
d = np.array([1,2,3,4,5,6],ndmin = 10)
print(d)
print(d.ndim)

[[[[[[[[[[1 2 3 4 5 6]]]]]]]]]]
10


In [39]:
g = np.zeros(5)
print(g)
print(type(g))
print(g.dtype)

[0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>
float64


In [42]:
h = np.zeros(5,dtype=int)
print(h)
print(type(h))
print(h.ndim)
print(h.dtype)

[0 0 0 0 0]
<class 'numpy.ndarray'>
1
int64


In [40]:
e = np.zeros([3,2])
print(e)
print(type(e))
print(e.ndim)
print(e.dtype)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>
2
float64


In [46]:
f = np.zeros([3,2],dtype=int)
print(e)
print(e.ndim)
print(e.dtype)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
2
float64


In [49]:
i = np.arange(1,31,5)
print(i)

[ 1  6 11 16 21 26]


In [53]:
j = np.zeros([3,3],dtype=int)
k = np.array(j,ndmin=10)
print(k)

[[[[[[[[[[0 0 0]
         [0 0 0]
         [0 0 0]]]]]]]]]]


In [54]:
j = np.array(np.zeros([3,3]),ndmin = 10)
print(j)

[[[[[[[[[[0. 0. 0.]
         [0. 0. 0.]
         [0. 0. 0.]]]]]]]]]]
