FIRST NUMPY CHECK

In [1]:
import numpy as np
print("NumPy version:", np.__version__)


NumPy version: 1.26.4


In [2]:
import numpy as np
a=np.array([1,5,6,7,8])

In [3]:
print(a)

[1 5 6 7 8]


2D ARRAY

In [5]:
b = np.array([[5,7,8,9]])
print(b)

[[5 7 8 9]]


3D ARRAY

In [8]:
b = np.array([[[5,7,8,9]]])
print(b)

[[[5 7 8 9]]]
